services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: varad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ../cortex_data/postgres:/var/lib/postgresql/data
    networks:
      - cortex-net

  minio-server:
    image: minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://host.docker.internal:8080/api/webhook/minio"
    volumes:
      - ../cortex_data/minio:/data
    networks:
      - cortex-net


  kafka:
    image: apache/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # KAFKA_LISTENERS: PLAINTEXT://localhost:29092,CONTROLLER://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - cortex-net

  kafka-console:
    container_name: kafka-console
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8090:8080"
    environment:
      - KAFKA_BROKERS=kafka-server:29092
    depends_on:
      - kafka
    networks:
      - cortex-net

  db-admin:
    container_name: db-admin
    image: adminer:latest
    ports:
      - "8978:8080"
    networks:
      - cortex-net
    depends_on:
      - postgres

  cortex-event-router:
    build:
      context: .
      dockerfile: cortex-event-router/Dockerfile
    container_name: cortex-event-router
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:29092
    depends_on:
      - kafka
    networks:
      - cortex-net

  cortex-ingestion:
    build:
      context: .
      dockerfile: cortex-ingestion/Dockerfile
    container_name: cortex-ingestion
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - MINIO_URL=http://minio-server:9000
      - MINIO_EXTERNAL_URL=http://localhost:9000
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:29092
    depends_on:
      - postgres
      - minio-server
      - kafka
      - cortex-event-router
    networks:
      - cortex-net

  cortex-media-processing-service:
    build:
      context: .
      dockerfile: cortex-media-processing-service/Dockerfile
    container_name: cortex-media-processing-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - MINIO_URL=http://minio-server:9000
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:29092
    depends_on:
      - postgres
      - minio-server
      - kafka
    networks:
      - cortex-net

networks:
  cortex-net:
    driver: bridge
